#!/bin/bash

set -eo pipefail

export PROJECT=multicore-magic
export DOCS=_build/default/_doc/_html/
export GIT=git@github.com:ocaml-multicore/$PROJECT.git

folded() {
  echo
  echo "JOB: $1"
  shift
  local TIMEFORMAT="CPU: %Us, Real: %Es"
  time "$@"
}
